owner: bgruening
name: split_file_to_collection
categories: 
  - Text Manipulation
description: Split tabular, MGF, FASTA, or FASTQ files to a dataset collection. 
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/split_file_to_collection
type: unrestricted
